services:
  front-end:
    build:
      context: ./front-end    
    depends_on:
      - back-end

  back-end:
    build:
      context: ./back-end
    
  proxy:
    build:
      context: ./proxy 
    ports:
      - 80:80
    depends_on:
      - front-end
      - back-end

#docker-compose build
#docker-compose up
